Issue #46: Clear raffle winner
crscillitoe/RoboBanana pull request #47
Opened 2023-01-12 17:11 UTC by benginerd

The previous manual solution was to write a script against the db using user_id and raffle_id. As far as I know, the user does not have access to the raffle_id. Therefore, this solution uses the user_id and looks for a raffle win occurring within the last 7 days.

2023-01-12 17:25 UTC, benginerd commented
https://streamable.com/2ryedl

2023-01-12 19:00 UTC, teknogeek requested changes

2023-01-12 19:01 UTC, teknogeek commented
LGTM overall, relying on the last 7 days is convenient and will save us from having to search for the message ID whenever we need to do a win reset from a modmail ticket

2023-01-12 19:18 UTC, benginerd commented on db/__init__.py
> +            RaffleEntry.user_id == user_id, RaffleEntry.winner == 1, RaffleEntry.timestamp > after).scalar()
Good point, I updated and believe I applied this. Let me know!

2023-01-14 20:01 UTC, teknogeek requested changes
LGTM otherwise

2023-01-15 18:59 UTC, benginerd commented on db/__init__.py
> +                .limit(1)
Heard, I believe I applied this feedback. Originally, I had the cooldown logic do the 7 day cooldown relative to the time of day the winner originally won their raffle (datetime.now() versus datetime.now().date() ); I agree that making the cooldown only use the days and not hours etc. makes more sense and is also more intuitive for the user.

2023-01-15 23:08 UTC, teknogeek approved these changes

2023-01-18 00:29 UTC, merged